### ISSUE TITLE
Annotation text not showing

### ISSUE THREAD

**Issue by ocervell** [frankie567/grafana-annotation-action#13]
Annotations are being POST'ed correctly, however I cannot see the text when hovering on of them in Grafana dashboard. I do see the annotation bar though.

**Comment by frankie567** [comment]
Indeed, the popover doesn't seem to show anymore. I don't think it's a problem coming from the action: I've tried to add an annotation manually and experience the same behaviour. Maybe Grafana introduced a change or bug recently?

**Comment by ocervell** [comment]
I think this is related to https://github.com/grafana/grafana/issues/40397.

**Comment by frankie567** [comment]
Looks like it has been fixed in Grafana v8.2.2: https://github.com/grafana/grafana/releases/tag/v8.2.2
